### ISSUE TITLE
[Request] Add CLI option to pass chrome flags to puppeteer

### ISSUE THREAD

**Issue by sanbornhilland** [nolanlawson/fuite#39]
First off, kudos on this project. I've been reading your blog posts as they come up on HN and I'm excited to see where you take this.

I'm working on an app that makes heavy use of audio and video inputs and in order to automate this I need to be able to launch chrome with some [flags](https://peter.sh/experiments/chromium-command-line-switches/) turned on. For now I've just manually updated the launch script to pass the arguments like this:

```js
const browser = await puppeteer.launch({
    headless: !debug,
    defaultViewport: { width: 1280, height: 800 },
    args: [
      '--use-fake-device-for-media-stream',
      '--use-file-for-fake-video-capture\=/path/to/webcam-audio-video-sync.y4m',
      '--use-file-for-fake-audio-capture\=/path/to/webcam-audio-video-sync.wav',
      '--use-fake-ui-for-media-stream',
    ],
  })
```

It would be useful to be able to pass these through the `fuite` CLI. Something like `fuite http://localhost:8080 -s tests/fuite/login.scenario.mjs --chrome-flags --use-fake-device-for-media-stream etc.`

**Comment by nolanlawson** [comment]
Thanks yeah, I figured this would come up at some point. `--chrome-flag` makes sense to me, but I wonder if there is some existing convention from another tool (Puppeteer, WebDriverIO, etc.) that I can borrow for this?

Looks like WebDriverIO calls it [`goog:chromeOptions` and `args`](https://stackoverflow.com/questions/32740900/webdriverio-selenium-pass-command-line-arguments-into-chrome-from-config-js-file), and Puppeteer calls it [`args`](https://stackoverflow.com/a/56249730). I'm kind of leaning towards calling it `--browser-args` since technically we're launching Chromium, not Chrome, but `--chromium-args` sounds a bit weird to me.
